package com.study.mybatismbg.mappers;

import com.study.mybatismbg.bean.TStorage;
import com.study.mybatismbg.bean.TStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    long countByExample(TStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int deleteByExample(TStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int insert(TStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int insertSelective(TStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    List<TStorage> selectByExample(TStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    TStorage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TStorage record, @Param("example") TStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TStorage record, @Param("example") TStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TStorage record);
}