package com.study.mybatismbg.bean;

import java.io.Serializable;

public class TStorage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage.used
     *
     * @mbg.generated
     */
    private Integer used;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage.residue
     *
     * @mbg.generated
     */
    private Integer residue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage.id
     *
     * @return the value of t_storage.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage.id
     *
     * @param id the value for t_storage.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage.product_id
     *
     * @return the value of t_storage.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage.product_id
     *
     * @param productId the value for t_storage.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage.total
     *
     * @return the value of t_storage.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage.total
     *
     * @param total the value for t_storage.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage.used
     *
     * @return the value of t_storage.used
     *
     * @mbg.generated
     */
    public Integer getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage.used
     *
     * @param used the value for t_storage.used
     *
     * @mbg.generated
     */
    public void setUsed(Integer used) {
        this.used = used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage.residue
     *
     * @return the value of t_storage.residue
     *
     * @mbg.generated
     */
    public Integer getResidue() {
        return residue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage.residue
     *
     * @param residue the value for t_storage.residue
     *
     * @mbg.generated
     */
    public void setResidue(Integer residue) {
        this.residue = residue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", total=").append(total);
        sb.append(", used=").append(used);
        sb.append(", residue=").append(residue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}