###
GET http://localhost:8401/testB
Accept: application/json

###
GET http://localhost:8401/testB
Accept: application/json

###
GET http://localhost:8401/testB
Accept: application/json

###
GET http://localhost:8401/testB
Accept: application/json

###
GET http://localhost:8401/testB
Accept: application/json

###
GET http://localhost:8401/testB
Accept: application/json

###
GET http://localhost:8401/testB
Accept: application/json

###
GET http://localhost:8401/testB
Accept: application/json